/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package reminderapplication;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vaisakh Viswanathan
 */
public class View_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form View_JPanel
     */
    Connection con;
    public View_JPanel() {
        try {
            initComponents();
            try {
                Class.forName("com.mysql.jdbc.Driver");
                try {
                    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/reminderapp_db","root","root");
                } catch (SQLException ex) {
                    Logger.getLogger(View_JPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(View_JPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            String s="Select * from reminder_tb";
            PreparedStatement ps=con.prepareStatement(s);
            ResultSet rs=ps.executeQuery();
            rs.last();
            int r=rs.getRow();
            rs.beforeFirst();
            Object[][] data=new Object[r][5];
            int i=0;
            while(rs.next())
            {
                
                data[i][0]=rs.getString(1);
                data[i][1]=rs.getString(2);
                data[i][2]=rs.getString(3);
                
                i++;
                
            }
            jTable1.setModel(new DefaultTableModel(data,new String[]{"ID","Date","Time","Message",}));
        } catch (SQLException ex) {
            Logger.getLogger(View_JPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Message"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
